### ISSUE TITLE
生成二进制文件报错，报错内容如下

### ISSUE THREAD

**Issue by ChaoYang-OPS** [n9e/wechat-sender#3]
main.go:16:2: cannot find package "." in:
	/usr/local/go/src/github.com/n9e/wechat-sender/config
main.go:17:2: cannot find package "." in:
	/usr/local/go/src/github.com/n9e/wechat-sender/cron
main.go:18:2: cannot find package "." in:
	/usr/local/go/src/github.com/n9e/wechat-sender/redisc
main.go:12:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/pkg/file
main.go:13:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/pkg/logger
main.go:14:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/pkg/runner

**Comment by UlricQin** [comment]
应该是GOPATH配置的有问题

**Comment by ChaoYang-OPS** [comment]
缺少依赖，已经解决，非常感谢
